version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: vault_postgres
    restart: always
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: vaultpass
      POSTGRES_DB: arkadevault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
